### ISSUE TITLE
New version number 2.0.0 is lower than the previous one

### ISSUE THREAD

**Issue by VyacheslavPritykin** [sma73648/identityserver-contrib-membership#6]
Current situation on nuget.org is:
IdentityServer3.Contrib.Membership 1.0.28
IdentityServer4.Contrib.Membership 4.0.28

New release https://github.com/sma73648/identityserver-contrib-membership/releases/tag/2.0.0 set the version number to 2.0.0 for both packages and it becomes lower than existing 4.0.28 for IdentityServer4.Contrib.Membership.

P.S. Thanks for bringing this project back to life 👍

**Comment by wwwlicious** [comment]
There was an issue with the build, hopefully should be fixed and I'll push v5 to nuget
